<?php
/**
 * @file
 * This is the installation file pack & upload module.
 *
 * All hooks related module installation and cleanup are mentioned here.
 */

/**
 * Implements hook_uninstall().
 */
function automateimport_uninstall() {
  variable_del('automateimport_bulk_media_path');
}

/**
 * Implements hook_install().
 */
function automateimport_install() {
  variable_set('automateimport_bulk_media_path', 'public://bulk_media');
}
